baseURL: "https://jshmnrd.ca" 
title: Joshua Maynard
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: About
          url: about/
          weight: 5 
        - name: Resume
          url: resume/
          weight: 2
        - name: D&D
          url: dnd/
          weight: 3
        - name: Tags
          url: tags/
          weight: 4 

params:
    description: "This is my personal website, where I keep pretty much whatever I want myself or others to be able to access freely."
    author: Joshua Maynard
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["about","resume","d&d"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Joshua Maynard
          subtitle: "I am a 25 year old from Toronto, Canada. I'm a geek. I love movies, TV, Dungeons & Dragons and pretty much anything computer-related."
          imageUrl: "https://pub.jshmnrd.ca/logo/taro-transparent.gif"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: About
              url: about/
            - name: Resume
              url: resume/
            - name: D&D
              url: dnd/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/

    socialIcons:
        - name: Twitter
          url: https://twitter.com/bigMoosse
        - name: Bluesky
          url: https://bsky.app/profile/jshmnrd.ca
        - name: Mastodon
          url: https://mstdn.ca/@jshmnrd
        - name: GitHub
          url: https://github.com/jshmnrd

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Joshua Maynard"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2