baseURL: "https://jshmnrd.ca" 
title: Joshua Maynard
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: about
          url: about/
          weight: 2 
        - name: d&d
          url: dnd/
          weight: 4
        - name: posts
          url: posts/
          weight: 3
        - name: tags
          url: tags/
          weight: 5

params:
    description: "This is my personal website, where I keep pretty much whatever I want myself or others to be able to access freely."
    author: Joshua Maynard
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: auto
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["about","posts","d&d"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Joshua Maynard
          subtitle: "I am a 25 year old from Toronto, Canada. I'm a geek. I love movies, TV, Dungeons & Dragons and pretty much anything computer-related."
          imageUrl: "jm-transparent.PNG"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: about
              url: about/
            - name: posts
              url: posts/
            - name: d&d
              url: dnd/
            - name: tags
              url: tags/

    socialIcons:
        - name: Twitter
          url: https://twitter.com/bigMoosse/
        - name: Bluesky
          url: https://bsky.app/profile/jshmnrd.ca/
        - name: Mastodon
          url: https://mstdn.ca/@jshmnrd/
        - name: Letterboxd
          url: https://letterboxd.com/jshmnrd/
        - name: Anilist
          url: https://anilist.co/user/joshuamaynard/
        - name: GitHub
          url: https://github.com/jshmnrd/
        - name: LinkedIn
          url: https://www.linkedin.com/in/maynardjoshua/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Joshua Maynard"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2